### PR TITLE
bump dateformat

### PR DESCRIPTION
**Pull request by jonschlinkert**
per https://github.com/felixge/node-dateformat/pull/53#issuecomment-245782776

### CODE REVIEW

**Comment by phated** [comment]
Did we say this was going to be a minor or patch?

**Comment by jonschlinkert** [comment]
> Did we say this was going to be a minor or patch?

patch since it removes the CLI in dateformat which wasn't exposed or accessible through gulp-util.  

thanks btw! hope you had a great thanksgiving

**Comment by jonschlinkert** [comment]
ping. @phated no rush, just wanted to ping in case you forgot. thanks

**Comment by phated** [comment]
@jonschlinkert thanks for the ping.  I had forgotten about this.  Weirdly enough, the npm website shows version 1.0.12 but `npm info` shows it at 2.0.0

**Comment by phated** [comment]
Published at 3.0.8

**Comment by jonschlinkert** [comment]
thank you! much appreciated

**Pull request merged**
